### PR TITLE
upgrade asm to really support java9

### PR DESCRIPTION
**Pull request by asolntsev**

### CODE REVIEW

**Comment by mkurz** [comment]
@asolntsev Why did you use `6.0_BETA`? At the time you opened the pull request 6.0 final was released already: https://gitlab.ow2.org/asm/asm/tags
Just asking, maybe there was a cause for this?
BTW: `6.1_BETA` is out already as well.

**Comment by mkurz** [comment]
BTW: It was tagged `6.1_BETA` but the jar name is lower case now with a dash instead of an underscore (looks like they changed it): https://mvnrepository.com/artifact/org.ow2.asm/asm/6.1-beta

**Comment by mkurz** [comment]
See #2

**Comment by asolntsev** [comment]
@mkurz I didn't have any particular reason for using `6.1_BETA`. I guess `6.1` was not released in Maven Central repository at that moment.

**Comment by mkurz** [comment]
FYI: ASM 6.2 released with better JDK 10 support and even with JDK 11 support already!
http://asm.ow2.io/versions.html
https://gitlab.ow2.org/asm/asm/tags
https://gitlab.ow2.org/asm/asm/issues/317830

**Pull request merged**
